// <auto-generated />
namespace WeatherProrok.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201601160959509_AddKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
